-- WAT-5: audience lesson attempts.
--
-- One row per audience submission. Multiple attempts per lesson are allowed
-- (no upsert/dedupe) — every submission is a brand-new row, so the report can
-- show every run. The lesson DEFINITION lives only in the creator's browser
-- (localStorage), so each attempt embeds a self-contained JSON `responses`
-- snapshot (per-slide question + the audience's answer + correctness). That
-- makes the report renderable from D1 alone, even on a different device.

CREATE TABLE IF NOT EXISTS attempts (
  -- UUID/text primary key (generated by the Worker via crypto.randomUUID()).
  id            TEXT PRIMARY KEY,
  -- The localStorage lesson id this attempt belongs to (e.g. lesson_<uuid>).
  lesson_id     TEXT NOT NULL,
  -- Optional free-text audience name captured on the start screen.
  audience_name TEXT,
  -- Number of response-bearing slides answered correctly.
  score         INTEGER NOT NULL DEFAULT 0,
  -- Total number of response-bearing (scored) slides in the lesson.
  total         INTEGER NOT NULL DEFAULT 0,
  -- JSON array of per-slide snapshots:
  --   [{ slideId, type, question, response, correct }, ...]
  -- `response`/`correct` shapes are slide-type-defined (generic — not pinned
  -- to pick-answer). Info-only slides are not included (no response).
  responses     TEXT NOT NULL DEFAULT '[]',
  -- ISO-8601 UTC timestamp of when the attempt was submitted.
  created_at    TEXT NOT NULL
);

-- Reports list all attempts for one lesson, newest first.
CREATE INDEX IF NOT EXISTS idx_attempts_lesson
  ON attempts (lesson_id, created_at DESC);
